### ISSUE TITLE
几个小问题

### ISSUE THREAD

**Issue by aenon** [LePtC/LePtC.github.io#1]
别忘了修改 favicon.ico, 还有游戏成功之后的话。

**Comment by LePtC** [comment]
感谢！另外这个游戏原本是玩到“生”就算成功了是么？...

**Comment by aenon** [comment]
html_actuator.js 里面有规则。我那一版是到“生”算成功。“生”对应的是2048.

**Comment by emptymalei** [comment]
这个有意思。要玩到什么样？

**Comment by LePtC** [comment]
@emptymalei ：就是加入那三个设定就行了，可是我不怎么会写 javascript ...

**Comment by emptymalei** [comment]
我现在明白了。我刚开始还在想为什么游戏名字带个 2048 ，看到你在果壳的那个问答就明白了……
